name: Build-Package-Deploy Workflow

on:
  push:
    branches:
      - main # Trigger build and package jobs on pushes to the main branch
  workflow_dispatch: # Allows manual trigger for deployment jobs

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Application
        run: |
          echo "Building the application..."
          # Add your build commands here

  package:
    name: Package Application
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Package Application
        run: |
          echo "Packaging the application..."
          # Add your packaging commands here

  dev-deploy:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    needs: package
    environment: 
      name: Dev # Maps to the Dev environment in GitHub settings
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Application to Dev
        run: |
          echo "Deploying to Dev..."
          # Add your deployment commands here

  qa-deploy:
    name: Deploy to QA
    runs-on: ubuntu-latest
    needs: package
    environment: 
      name: QA # Maps to the QA environment in GitHub settings
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Application to QA
        run: |
          echo "Deploying to QA..."
          # Add your deployment commands here

  uat-deploy:
    name: Deploy to UAT
    runs-on: ubuntu-latest
    needs: package
    environment: 
      name: UAT # Maps to the UAT environment in GitHub settings
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Application to UAT
        run: |
          echo "Deploying to UAT..."
          # Add your deployment commands here

          
